import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Link from 'next/link';
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import Dummy from "@/components/dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    {/* <style jsx>
      {`
      .mySpan{
        background-color: red;
      }
      `}
    </style> */}
    {/* <Dummy/> */}
      <Head>
        <title>Insight Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Next.js, InsightBlogs, coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src='' strategy="lazyOnload">
        
      </Script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blogs</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={`${styles.main}`}>
        <div className={styles.center}>
          <h1>Insights Blogs</h1>
        </div>
          <p>
            A blog for coders from a coder
          </p>
        <div className="blogs">
        <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  );
}
